name: keepswitch
description: A Beautiful custom Switch for your tiles. With granular control over the look and feel.
version: 0.0.1
homepage: https://github.com/ProblematicDude/keepswitch

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
